/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Lord Negrisoli
 */
import javax.swing.*;
public class Objetivas extends javax.swing.JFrame {

    /**
     * Creates new form Objetivas
     */
    public Objetivas() {
        initComponents();
        this.setLocationRelativeTo(null);
        qtdQ.setEnabled(true);
        gravarQtd.setEnabled(true);
        valorProva.setEnabled(false);
        gravarValor.setEnabled(false);
        mediaAp.setEnabled(false);
        gravarAp.setEnabled(false);
        criarG.setEnabled(false);
        exibirG.setEnabled(false);
        corrigir.setEnabled(false);
        nomeAluno.setEnabled(false);
        alternativaA.setEnabled(false);
        valorQ.setEnabled(false);
        exibirA.setEnabled(false);
    }
    CorretorObjetivas objetivas = new CorretorObjetivas();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        qtdQ = new javax.swing.JTextField();
        gravarQtd = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        valorProva = new javax.swing.JTextField();
        gravarValor = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        mediaAp = new javax.swing.JTextField();
        gravarAp = new javax.swing.JButton();
        criarG = new javax.swing.JButton();
        exibirG = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        exibirA = new javax.swing.JButton();
        alternativaA = new javax.swing.JButton();
        label = new javax.swing.JLabel();
        nomeAluno = new javax.swing.JTextField();
        corrigir = new javax.swing.JButton();
        valorQ = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel3.setText("Desenvolvido por Victor Hugo Negrisoli & Natália Cristina Martins de Sá");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/livro_00000.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Rockwell Condensed", 3, 36)); // NOI18N
        jLabel1.setText("Corretor de Provas 5.0");

        jLabel4.setText("Quantidade de questões:");

        qtdQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtdQActionPerformed(evt);
            }
        });

        gravarQtd.setText("Gravar");
        gravarQtd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gravarQtd.setEnabled(false);
        gravarQtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gravarQtdActionPerformed(evt);
            }
        });

        jLabel5.setText("Valor da prova:");

        valorProva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorProvaActionPerformed(evt);
            }
        });

        gravarValor.setText("Gravar");
        gravarValor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gravarValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gravarValorActionPerformed(evt);
            }
        });

        jLabel6.setText("Média para aprovação:");

        mediaAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mediaApActionPerformed(evt);
            }
        });

        gravarAp.setText("Gravar");
        gravarAp.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gravarAp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gravarApActionPerformed(evt);
            }
        });

        criarG.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        criarG.setText("Criar gabarito!");
        criarG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        criarG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarGActionPerformed(evt);
            }
        });

        exibirG.setText("Exibir gabarito");
        exibirG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exibirG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirGActionPerformed(evt);
            }
        });

        exibirA.setText("Exibir alternativas");
        exibirA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exibirA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exibirAActionPerformed(evt);
            }
        });

        alternativaA.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        alternativaA.setText("Alternativas do aluno!");
        alternativaA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        alternativaA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alternativaAActionPerformed(evt);
            }
        });

        label.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        label.setText("Digite o nome do aluno:");

        nomeAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeAlunoActionPerformed(evt);
            }
        });

        corrigir.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        corrigir.setText("Corrigir!");
        corrigir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        corrigir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                corrigirActionPerformed(evt);
            }
        });

        valorQ.setText("Valor das questões");
        valorQ.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        valorQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                valorQActionPerformed(evt);
            }
        });

        jButton3.setText("Sair");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Voltar");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Nova correção");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(valorProva)
                            .addComponent(gravarValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(mediaAp)
                            .addComponent(gravarAp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addComponent(jButton5)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(qtdQ)
                            .addComponent(gravarQtd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(corrigir, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(exibirG, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(criarG, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nomeAluno)
                                    .addComponent(label, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(valorQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exibirA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(alternativaA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(qtdQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gravarQtd))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(valorProva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gravarValor))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mediaAp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(gravarAp)
                            .addComponent(jButton5))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(criarG, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(valorQ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(10, 10, 10)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(alternativaA, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(exibirA)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(label)
                                .addComponent(exibirG)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nomeAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(corrigir, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gravarApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gravarApActionPerformed
        try{
            mediaAp.setEnabled(false);
            gravarAp.setEnabled(false);
            criarG.setEnabled(true);
            exibirG.setEnabled(true);
            corrigir.setEnabled(true);
            nomeAluno.setEnabled(true);
            alternativaA.setEnabled(true);
            exibirA.setEnabled(true);
            objetivas.mediaParaAprovacao(Integer.parseInt(mediaAp.getText()));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Por favor, insira algum valor no campo.");
            mediaAp.setEnabled(true);
            gravarAp.setEnabled(true);
            criarG.setEnabled(false);
            exibirG.setEnabled(false);
            corrigir.setEnabled(false);
            nomeAluno.setEnabled(false);
            alternativaA.setEnabled(false);
            exibirA.setEnabled(false);
        }
    }//GEN-LAST:event_gravarApActionPerformed

    private void gravarQtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gravarQtdActionPerformed
        try{
            valorProva.setEnabled(true);
            gravarValor.setEnabled(true);
            qtdQ.setEnabled(false);
            gravarQtd.setEnabled(false);
            objetivas.quantidadeDeQuestoes(Integer.parseInt(qtdQ.getText()));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Por favor, insira algum valor no campo.");
            valorProva.setEnabled(false);
            gravarValor.setEnabled(false);
            qtdQ.setEnabled(true);
            gravarQtd.setEnabled(true);
        }
    }//GEN-LAST:event_gravarQtdActionPerformed

    private void gravarValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gravarValorActionPerformed
        try{    
            mediaAp.setEnabled(true);
            gravarAp.setEnabled(true);
            valorProva.setEnabled(false);
            gravarValor.setEnabled(false);
            objetivas.valorTotalDaProva(Integer.parseInt(valorProva.getText()));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Por favor, insira algum valor no campo.");
            mediaAp.setEnabled(false);
            gravarAp.setEnabled(false);
            valorProva.setEnabled(true);
            gravarValor.setEnabled(true);
        }
    }//GEN-LAST:event_gravarValorActionPerformed

    private void criarGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarGActionPerformed
        objetivas.setGabarito();
    }//GEN-LAST:event_criarGActionPerformed

    private void mediaApActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mediaApActionPerformed
        try{
            mediaAp.setEnabled(false);
            gravarAp.setEnabled(false);
            criarG.setEnabled(true);
            exibirG.setEnabled(true);
            corrigir.setEnabled(true);
            nomeAluno.setEnabled(true);
            alternativaA.setEnabled(true);
            exibirA.setEnabled(true);
            objetivas.mediaParaAprovacao(Integer.parseInt(mediaAp.getText()));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Por favor, insira algum valor no campo.");
            mediaAp.setEnabled(true);
            gravarAp.setEnabled(true);
            criarG.setEnabled(false);
            exibirG.setEnabled(false);
            corrigir.setEnabled(false);
            nomeAluno.setEnabled(false);
            alternativaA.setEnabled(false);
            exibirA.setEnabled(false);
        }
    }//GEN-LAST:event_mediaApActionPerformed

    private void alternativaAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativaAActionPerformed
        valorQ.setEnabled(true);
        objetivas.respostasAluno();
    }//GEN-LAST:event_alternativaAActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Menu menu = new Menu();
        menu.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        JOptionPane.showMessageDialog(null, "Todas as informações foram apagadas");
        qtdQ.setEnabled(true);
        gravarQtd.setEnabled(true);
        valorProva.setEnabled(false);
        gravarValor.setEnabled(false);
        mediaAp.setEnabled(false);
        gravarAp.setEnabled(false);
        criarG.setEnabled(false);
        exibirG.setEnabled(false);
        corrigir.setEnabled(false);
        nomeAluno.setEnabled(false);
        alternativaA.setEnabled(false);
        valorQ.setEnabled(false);
        exibirA.setEnabled(false);
        qtdQ.setText("");
        mediaAp.setText("");
        valorProva.setText("");
        nomeAluno.setText("");
        objetivas = new CorretorObjetivas();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void qtdQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtdQActionPerformed
        try{
            valorProva.setEnabled(true);
            gravarValor.setEnabled(true);
            qtdQ.setEnabled(false);
            gravarQtd.setEnabled(false);
            objetivas.quantidadeDeQuestoes(Integer.parseInt(qtdQ.getText()));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Por favor, insira algum valor no campo.");
            valorProva.setEnabled(false);
            gravarValor.setEnabled(false);
            qtdQ.setEnabled(true);
            gravarQtd.setEnabled(true);
        }
    }//GEN-LAST:event_qtdQActionPerformed

    private void exibirGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirGActionPerformed
        objetivas.exibirGabarito();
    }//GEN-LAST:event_exibirGActionPerformed

    private void valorQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorQActionPerformed
        objetivas.valorDasQuestoes();
    }//GEN-LAST:event_valorQActionPerformed

    private void corrigirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_corrigirActionPerformed
        try{    
            objetivas.mostrarRespostas(nomeAluno.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos para continuar.");
        }
    }//GEN-LAST:event_corrigirActionPerformed

    private void exibirAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exibirAActionPerformed
        objetivas.exibirAlternativas();
    }//GEN-LAST:event_exibirAActionPerformed

    private void valorProvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_valorProvaActionPerformed
        try{    
            mediaAp.setEnabled(true);
            gravarAp.setEnabled(true);
            valorProva.setEnabled(false);
            gravarValor.setEnabled(false);
            objetivas.valorTotalDaProva(Integer.parseInt(valorProva.getText()));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Por favor, insira algum valor no campo.");
            mediaAp.setEnabled(false);
            gravarAp.setEnabled(false);
            valorProva.setEnabled(true);
            gravarValor.setEnabled(true);
        }
    }//GEN-LAST:event_valorProvaActionPerformed

    private void nomeAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeAlunoActionPerformed
        try{    
            objetivas.mostrarRespostas(nomeAluno.getText());
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos para continuar.");
        }
    }//GEN-LAST:event_nomeAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Objetivas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Objetivas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Objetivas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Objetivas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Objetivas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alternativaA;
    private javax.swing.JButton corrigir;
    private javax.swing.JButton criarG;
    private javax.swing.JButton exibirA;
    private javax.swing.JButton exibirG;
    private javax.swing.JButton gravarAp;
    private javax.swing.JButton gravarQtd;
    private javax.swing.JButton gravarValor;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel label;
    private javax.swing.JTextField mediaAp;
    private javax.swing.JTextField nomeAluno;
    private javax.swing.JTextField qtdQ;
    private javax.swing.JTextField valorProva;
    private javax.swing.JButton valorQ;
    // End of variables declaration//GEN-END:variables
}
